-- drop external table azureMetrics;
CREATE EXTERNAL TABLE [dbo].[azureMetrics]
( 	[TenantId] varchar(100) ,
	[SourceSystem] varchar(50) ,
	[TimeGenerated] varchar(50) ,
	[ResourceId] varchar(400) ,
	[OperationName] varchar(100) ,
	[OperationVersion] varchar(100) ,
	[Category] varchar(100) ,
	[ResultType] varchar(100) ,
	[ResultSignature] varchar(100) ,
	[ResultDescription] varchar(100) ,
	[DurationMs] real ,
	[CallerIpAddress] varchar(100) ,
	[CorrelationId] varchar(100) ,
	[Resource] varchar(100) ,
	[ResourceGroup] varchar(100) ,
	[ResourceProvider] varchar(100) ,
	[SubscriptionId] varchar(100) ,
	[MetricName] varchar(100) ,
	[Total] varchar(50) ,
	[Count] varchar(50) ,
	[Maximum] varchar(50) ,
	[Minimum] varchar(50),
	[Average] varchar(50) ,
	[TimeGrain] varchar(10) ,
	[UnitName] varchar(50),
	[RemoteIPCountry] varchar(50) ,
	[RemoteIPLatitude] varchar(50) ,
	[RemoteIPLongitude] varchar(50) ,
	[MaliciousIP] varchar(50) ,
	[IndicatorThreatType] varchar(100) ,
	[Description] varchar(400) ,
	[TLPLevel] varchar(100) ,
	[Confidence] varchar(100) ,
	[Severity] varchar(100),
	[FirstReportedDateTime] varchar(50) ,
	[LastReportedDateTime] varchar(50) ,
	[IsActive] varchar(1),
	[ReportReferenceLink] varchar(100) ,
	[AdditionalInformation] varchar(400) ,
	[Type] varchar(50) ,
	[_ResourceId] varchar(400)
)
WITH
 (
    LOCATION='/AzureMetrics/' ,
    DATA_SOURCE = StorageParquetLogFiles ,
    FILE_FORMAT = AS_PARQUET   
) ; 
GO
