name: data-pipeline-poc

env:
  LOCATION: eastus2

  resource_group_name: data-pipeline-rg
  log_analytics_workspace_name: data-pipeline-log
  data_lake_name: datapipelinedl
  data_lake_file_system_name: datapipelinefs
  data_lake_account_tier: standard
  data_lake_account_kind: StorageV2
  data_lake_account_replication_type: GRS
  data_lake_allow_blob_public_access: false
  keyvault_name: datapipelinekv
  keyvault_sku: standard
  secret_name_admin_user: sql-db-admin-user-name
  secret_name_admin_password: sql-db-admin-user-password
  key_vault_diagnostic_monitoring_name: dmon-kvt-datapipeline
  data_lake_diagnostic_monitoring_name: dmon-dlk-datapipeline
  dacpac_path: ./SQLScripts/DataWarehouse/Publish/DataWarehouse.dacpac
  dacpac_publish_path: .\publish

on:
  push:
   branches: [ main ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Connect to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Terraform Init
      run: |
        terraform init
        terraform plan -no-color
        terraform apply -auto-approve
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_ACCESS_KEY: ${{ secrets.TFSTATE_STORAGE_ACCT_KEY }}        
        TF_VAR_location: ${{ env.LOCATION }}
        TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_resource_group_name: ${{ env.resource_group_name }}
        TF_VAR_log_analytics_workspace_name: ${{ env.log_analytics_workspace_name }}
        TF_VAR_data_lake_name: ${{ env.data_lake_name }}
        TF_VAR_data_lake_file_system_name: ${{ env.data_lake_file_system_name }}
        TF_VAR_data_lake_account_tier: ${{ env.data_lake_account_tier }}
        TF_VAR_data_lake_account_replication_type: ${{ env.data_lake_account_replication_type }}
        TF_VAR_data_lake_account_kind: ${{ env.data_lake_account_kind }}
        TF_VAR_data_lake_allow_blob_public_access: ${{ env.data_lake_allow_blob_public_access }}
        TF_VAR_keyvault_name: ${{ env.keyvault_name }}
        TF_VAR_keyvault_sku: ${{ env.keyvault_sku }}        
        TF_VAR_secret_name_admin_user: ${{ env.secret_name_admin_user }}
        TF_VAR_secret_value_admin_user: ${{ secrets.SQL_ADMIN_USER_NAME }}
        TF_VAR_secret_name_admin_password: ${{ env.secret_name_admin_password }}
        TF_VAR_secret_value_admin_password: ${{ secrets.SQL_ADMIN_USER_PASSWORD }}      
        TF_VAR_key_vault_diagnostic_monitoring_name: ${{ env.key_vault_diagnostic_monitoring_name }}
        TF_VAR_data_lake_diagnostic_monitoring_name: ${{ env.data_lake_diagnostic_monitoring_name }}